name: "Terraform Apply"

on:
  push:
    branches:
    - main

env:
  CONFIG_DIRECTORY: "./"
  TF_HTTP_USERNAME: ${{ vars.TF_HTTP_USERNAME }}
  TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_cloudflare_email_catch_all_address: ${{ secrets.TF_VAR_cloudflare_email_catch_all_address }}

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color -input=false -auto-approve
        continue-on-error: true